package golog

import (
	"context"
	"log"
)

type (
	// Verbose levels
	Verbose uint8
	// Logger interface
	Logger interface {
		Debug(ctx context.Context, v string)
		Info(ctx context.Context, v string)
		Warning(ctx context.Context, v string)
		Error(ctx context.Context, v string)
		Critical(ctx context.Context, v string)
		// Fatal is equivalent to Critical followed by a call to os.Exit(1).
		Fatal(ctx context.Context, v string)

		// SetFlags override DefaultFlags value on a Logger instance https://golang.org/pkg/log/#pkg-constants
		SetFlags(flag int)
		// SetVerbosity override DefaultVerbosity value on a Logger instance
		SetVerbosity(verbosity Verbose)
	}

	loggerFactory func() Logger
)

// Verbose level flags
const (
	Critical Verbose = 1 << iota // Critical verbose level
	Error                        // Error verbose level
	Warning                      // Warning verbose level
	Info                         // Info verbose level
	Debug                        // Debug verbose level
	Disabled                     // Disabled verbose level disables logger messages. will override all other flags, fatal will still call os.Exit(1)
)

const (
	// DebugPrefix text to prefix to each log entry generated by the Logger
	DebugPrefix = "DEBUG: "
	// InfoPrefix text to prefix to each log entry generated by the Logger
	InfoPrefix = "INFO: "
	// WarnPrefix text to prefix to each log entry generated by the Logger
	WarnPrefix = "WARN: "
	// ErrorPrefix text to prefix to each log entry generated by the Logger
	ErrorPrefix = "ERROR: "
	// CriticalPrefix text to prefix to each log entry generated by the Logger
	CriticalPrefix = "CRITICAL: "

	// DefaultFlags define default text to prefix to each log entry generated by the Logger
	DefaultFlags = log.Ldate | log.Ltime | log.Lmicroseconds | log.LUTC
	// DefaultVerbosity define default verbosity level
	DefaultVerbosity = Critical | Error | Warning | Info | Debug
)

// New returns a Logger.
var New loggerFactory
