package golog

import (
	"context"
	"log"
)

// Verbose level
type Verbose int

const (
	// Critical verbose level
	Critical Verbose = iota // 0
	// Error verbose level
	Error // 1
	// Warning verbose level
	Warning // 2
	// Info verbose level
	Info // 3
	// Debug verbose level
	Debug // 4
	// Disabled verbose level disables logger messages
	Disabled Verbose = -1

	// DebugPrefix text to prefix to each log entry generated by the Logger
	DebugPrefix = "DEBUG: "
	// InfoPrefix text to prefix to each log entry generated by the Logger
	InfoPrefix = "INFO: "
	// WarnPrefix text to prefix to each log entry generated by the Logger
	WarnPrefix = "WARN: "
	// ErrorPrefix text to prefix to each log entry generated by the Logger
	ErrorPrefix = "ERROR: "
	// FatalPrefix text to prefix to each log entry generated by the Logger
	FatalPrefix = "FATAL: "

	// DefaultFlags define default text to prefix to each log entry generated by the Logger
	DefaultFlags = log.Ldate | log.Ltime | log.Lmicroseconds | log.LUTC
)

type (
	// Logger interface
	Logger interface {
		Debug(ctx context.Context, format string, args ...interface{})
		Info(ctx context.Context, format string, args ...interface{})
		Warning(ctx context.Context, format string, args ...interface{})
		Error(ctx context.Context, format string, args ...interface{})
		Critical(ctx context.Context, format string, args ...interface{})

		// Override DefaultFlags value on a Logger instance
		SetFlags(flag int)
	}

	loggerFactory func(level Verbose) Logger
)

// New returns a Logger.
var New loggerFactory
